namespace ORM.Core.Enums
{
    public enum TokenType
    {
        EOF,
        ClassKeyword,
        IntKeyword,
        FloatKeyword,
        StringKeyword,
        WhereKeyword,
        SelectKeyword,
        Identifier,
        IntConstant,
        FloatConstant,
        Plus,
        GreaterThan,
        LessThan,
        LeftParens,
        RightParens,
        SemiColon,
        NotEqual,
        Equal,
        OpenBrace,
        CloseBrace,
        Dot,
        And,
        Or,
        Comma,
        StringConstant,
        Arrow,
        EqualOperator,
    }
}